[package]
name = "e_image"
version = "0.1.0"
authors = ["Desmond Germans <desmond@germansmedia.nl>"]
edition = "2018"

[lib]
name = "e_image"
crate-type = ["rlib"]

[dependencies]
e_base = { version = "*", path = "../e_base" }